### ISSUE TITLE
Latest Beta - Doesnt recognize Somfy Screens as Window Covering

### ISSUE THREAD

**Issue by mruiter** [hive/com.groups#25]
Also not as a sun screen ot Jaloezieën and Lamellen.
On non of these grouped devices they show up when finding the devices

**Comment by hive** [comment]
Did this work in the previous beta?

Which capabilities are you selecting?

I am going to guess hat your using the AthomBV Somfy RTS? Which I cant view the code off to confirm that its not using custom capabilities. 


Somfy

**Comment by mruiter** [comment]
They worked with the version Of bas . 
I just switched to youre version (WoW Nice rewrite by the way 👍 ) for the Homey V2 support

Im indeed using Somfy rts app for the screens

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
I talked to the dev at athoms that does the Somfy app .

windowcoverings is the class the Somfy devices are in

**Comment by mruiter** [comment]
I found the right setting for Somfy. 
The only capability to select is state . Then iT finds the Somfy screens

**Comment by hive** [comment]
Great to know, that capability is available with in window-coverings as well as curtains, blinds and sunshades, there were changes in v2.0 of homey which mean that you can use what ever category (deviceClass) you want. Just so long as the capability is correct (windowcoverings_state). 



mean that you can use which ever category (deviceClass) you like, so long as the capability is correct.
