### ISSUE TITLE
Transition of IKEA bulbs when grouped not working

### ISSUE THREAD

**Issue by mhoogenbosch** [hive/com.groups#33]
See also https://community.athom.com/t/app-group-2-1-7/3168/123?u=martijn_hoogenbosch

**Comment by hive** [comment]
Just some background information, This undocumented 'feature' can be found it line 72 of the beta branch - not stable? https://github.com/athombv/com.ikea.tradfri/blob/beta/app.json


When investigating this issue I was able to add dim/hue/saturation transitions but it only works on devices it has been added to by the developer - and as it is undocumented I imagine that is only a few apps.

**Comment by hive** [comment]
For others 

replace ./drivers/light/driver.compose.json with the following : 

```
{
    "id": "light",
    "class": "light",
    "capabilities": [],
    "name": {
        "en": "Light",
        "nl": "Lamp"
    },
    "capabilitiesOptions": {
        "dim": {
            "opts": {
                "duration": true
            }
        },
        "light_hue": {
            "opts": {
                "duration": true
            }
        },
        "light_saturation": {
            "opts": {
                "duration": true
            }
        },
        "light_temperature": {
            "opts": {
                "duration": true
            }
        }
    },
    "$extends": [
        "default"
    ]
}
```
