### ISSUE TITLE
tried to change color, no go

### ISSUE THREAD

**Issue by ewognum** [hive/com.groups#34]
When i start up the HUE lights all Ok, They go on or off. But when i want to change the color it sticks to warm light and daylight colors. When i want to change the color it simply goes back to the saturation of the lights. 
But when i first change the color of the lamps it self then i can change the color of the lamps. Strange thing also is that the app it self still goes back to the saturation of the lamps and does not show which color it is currently producing.

Regards,

Edgar

**Comment by hive** [comment]
Hi,

Can you just confirm that you have added the capability called “light mode” into the group?

That’s how homey tell the lights to swap modes between hue / saturation and temperature.

Thanks

**Comment by ewognum** [comment]
Pfffff, sorry for the late reply, but yeah, totally missed this one. Now it all works like a charm.

Thanks
