### ISSUE TITLE
All groups triggered

### ISSUE THREAD

**Issue by BusterKrabba** [hive/com.groups#35]
After recent version upgrade all groups are triggered irrespective of that only one group card is selected under “when” in flows

**Comment by hive** [comment]
Hi, 

Can you please provide a screenshot of your flow?

Thanks

**Comment by hive** [comment]
Hi @BusterKrabba I am closing this issue and assuming that the problem has resolved itself, due to lack of information.

Please let me know if you have more information and ill open it up again.

Regards.

**Comment by BusterKrabba** [comment]
Hi Jamie
I deleted, reininstalled and reconfigured the app. After that no problems
Regards
Buster


15 apr. 2019 kl. 04:41 skrev Jamie <notifications@github.com<mailto:notifications@github.com>>:


Closed #35<https://github.com/hive/com.groups/issues/35>.
