### ISSUE TITLE
Unstable working with Philips hue lights

### ISSUE THREAD

**Issue by aliktab** [hive/com.groups#40]
I have several groups with Philips hue lamps. In flow I'm changing: Dim level, Saturation, Hue. Sometimes some of the parameters update the only some lamps in the group. 

The group "Kitchen Table Light" consists of 4 lamps "Kitchen Table ??". Screen 1  is before flow has been started, the Screen 2 is after. The only one lamp has changed color to white.

![1](https://user-images.githubusercontent.com/7151343/55663115-e53ec180-581a-11e9-886e-f33caa092bb4.jpg)
![2](https://user-images.githubusercontent.com/7151343/55663116-e53ec180-581a-11e9-9982-ef14859ff51f.jpg)
![flow](https://user-images.githubusercontent.com/7151343/55663117-e5d75800-581a-11e9-90dc-277eabade47b.jpg)

**Comment by Jamie-Peake** [comment]
Hey @aliktab 

There are two mis-understandings which can cause the results you are seeing. 

Either your group is missing the 'light_mode' capability. This is what tells the light whether to be in hue/saturation/temp mode. If a light (any light) is in temperature mode (white) then it is impossible to set its colour to 'red'. 

Or it could be that your trying to change the settings of a light which is 'off'. The underlying library which Athom uses to control HUE lights will error if you attempt to change the colour of a light which is off. You can update your group to only show as 'on' if all devices are on. 


Please keep me updated on how you go.

Thanks

**Comment by aliktab** [comment]
I don't change the settings of light separately for lamps in the group, I'm working via group object only. When I change the settings from the mobile app interface of the group device everything is working good. After that some runs of the flow are working good but then suddenly some lights (random lights) are stopping react on changes of some parameters (sometime color, sometime dim level). Then after some runs of the flow begins to work again.
light_mode parameter is in the group, see the Screeshot.

The problem is not with the color only. The dim level also simetimes wasn't set from the first run of the flow.

I've changed group to only show as 'on' if all devices are on but it doesn't help.

Actually it looks like the group think that the lamp already have parameter set to needed value and don't set it again in case of optimization.

![IMG_0325](https://user-images.githubusercontent.com/7151343/55674732-fe964b00-58b8-11e9-916d-1280aa839075.jpg)

**Comment by Jamie-Peake** [comment]
> Actually it looks like the group think that the lamp already have parameter set to needed value and don't set it again in case of optimization.

Thats correct, that was added as a form as optimization as well as a way to prep the addition of dynamic groups later on. (ie. have a group with colour, dim, and on/off - and add lights which only have an on/off to it as well as lights with on/off and dim and a devices with all three capbilities. When you hit on/off all three lights change state. But when you hit colour only the lights with colours change color.) 

If your able to contact me on Slack, we should be able to work together to find a solution. Otherwise please send me your Homey email address on the forums and I will create an alpha with the optimization turned off so we can see if it fixes your issue.

**Comment by aliktab** [comment]
Hi,
my e-mail in community: aliktab@gmail.com
my skype: aliktabunov
slack: alik@g5e.com

Hm, my problem is a little bit different. I set dim level for the group and some lamps in this group haven't received then new dim level. It looks like not differentiation by parameters it looks like the group device checks if the parameter value already was set for particular lamp and don't set it again for this lamp.

**Comment by Jamie-Peake** [comment]
`
 // Sanity, only update the devices which require updating : note there *could* be an issue with this when a gateway times out.
if (a.instance.value !== values[capability]) {
	a.instance.setValue(values[capability]);
}
`

**Comment by aliktab** [comment]
Hi Jamie,

I'm sorry but could you please allow this build for the main.tabunov@gmail.com because I use it for my homey. I can't add my second e-mail to homey because they have a bug.

When I use lamps directly they always work well. It looks like Homey have a bug with updating "instance.value"

**Comment by Jamie-Peake** [comment]
> It looks like Homey have a bug with updating "instance.value" 

- That wouldn't surprise me. 

I've changed the email address to the new one supplied.

**Comment by aliktab** [comment]
Got it, will check today evening and let you know the result.

**Comment by aliktab** [comment]
Hi Jamie,

Now everything is working good after fix.

**Comment by aliktab** [comment]
Hi Jamie,
Are you going to put this fix in release version or I have to disable autoupdate for this app?

**Comment by Jamie-Peake** [comment]
I am still testing this change locally. I have noticed a couple of issues but they may be unrelated and instead be a by-product of reinstalling a large part of the zWave mesh. 

Ill let you know.

**Comment by aliktab** [comment]
Hi Jamie,
Do you know that Homey starts all cards in one flow simultaneously in different threads? This may be the root of problem when I set several lamp properties in one flow at the same time.

**Comment by Friedi1970** [comment]
Hmm. This discussion meets my problem with groups ;)
Actually groups works fine for me. When I use 3 or 2 HUEs. But in one case of 5 HUEs I have problems and I just switch on and off. Sometimes all HUEs work sometimes not. Often, when I switch of 1 or 2 HUEs stay on or, when switching on, the other way round.
When I use the HUEs as single lamp I have no problems. Everything is working fine. So I assume there is a problem in Groups.

**Comment by hive** [comment]
The app it self does not 'do' actions, in fact it doesn't even ask the device to 'do' the action. It asks homey to ask the device to do an action. 

For example :

In this case, the group app does not 'turn on/off' the lights, it will ask homey to ask the device to turn off. 

Setting a value is actually the simplest thing that this app does, the complexity comes in for other actions. 

1. [When a user changes a groups capability (eg. on/off)](https://github.com/hive/com.groups/blob/a605a61cb222201e7804856e34461ef16f454e81/lib/device.js#L168-L171)
2. [Loop through each device in the group ](https://github.com/hive/com.groups/blob/a605a61cb222201e7804856e34461ef16f454e81/lib/device.js#L187)
3. [Loop through each capability which has changed](https://github.com/hive/com.groups/blob/a605a61cb222201e7804856e34461ef16f454e81/lib/device.js#L189)
4. [Set the capability to the value requested. ](https://github.com/hive/com.groups/blob/a605a61cb222201e7804856e34461ef16f454e81/lib/device.js#L201)

There is literally 5 lines code

---

As far as I can see with in the logs the group app is asking homey to its magic every time, with out issue. What homey does with the request is completely out of my hands. 

It has been reported previously, by many people for a long time that there is an issue with Homey trying to send multiple commands at one time, when Athom fix this I imagine that you will stop having issues. 

In the mean time, there is this feature request from Jaxc back in January : https://github.com/hive/com.groups/issues/7 - feel free to add a comment, but given that a lot of users also complain about the speed of the lights turning on I am not sure if it will ever be introduced.

**Comment by Friedi1970** [comment]
Got you but
> but given that a lot of users also complain about the speed of the lights turning on 

When I switch all the (same) lights by accessing each one individual but also in one single flow it looks like all of them switching immediately. If there is a problem of multiple commands why doesn't it occur when not using groups bus all of them in one flow?

**Comment by hive** [comment]
You can read about the speed (re: delay) issues upon the forum : https://community.athom.com/t/app-group-2-3-1-stable/3168/137?u=jamie - from Feb 26th until April. 

---


You would have to ask Athom that question, its pretty common issue - perhaps you're just lucky?  

I simply can not see how the code `a.instance.setValue(values[capability]);`, which simply asks homey to set a value :  could be affecting the sending and receiving of signals across multiple frequencies. (I have notice this issue in large Zwave groups).

**Comment by hive** [comment]
@aliktab - Another alpha release will be going out shortly, it still contains the requested change you made. Ill let you know if that gets removed. 


@Friedi1970 - Are you able to create a new issue, which has as much information as you can gather as to what is happening and when it happens. I will look into the problem, and ill update you on whether I can do anything about it. Anecdotally I've noticed when I see it occur on Zwave group - its always the same device which 'bugs out'.

**Comment by hive** [comment]
The fixed requested aliktab has been tested and will deployed to the app. I should warn you, even though I am no longer doing an sanity check prior to setting a device - that doesn't mean that Athom / Device is not. 

For example i've noticed that if a Fibaro dual switch wrongly shows as off when it is on - it never gets updated by the group :-(.

I have however added code which will attempt to change the value of the device a second time if I am notified the first time failed and finally added the ability to delay updating a device - which in the past has fixed issue on the flows. 

Please let me know how you go.

Thanks

**Comment by hive** [comment]
Closing, no feedback for a month.
