### ISSUE TITLE
Error since last homey update: session_timeout

### ISSUE THREAD

**Issue by romigithub** [hive/com.groups#41]
Error since last homey update: session_timeout

**Comment by BusterKrabba** [comment]
Same for me. None of the flows with Cards of Groups works.

**Comment by hive** [comment]
This is an issue with the Homey Core which has been fixed in the latest release candidate.

However if you don't want to wait there is a quick fix with in the group thread on the forums. 

https://community.athom.com/t/app-group-2-3-1-stable/3168/162?u=jamie

Thanks
