### ISSUE TITLE
Error while grouping Qubino ZMNHCD1 Flush Shutter.

### ISSUE THREAD

**Issue by Frankman66** [hive/com.groups#42]
First - great app. Unfortunately the grouping of the shutter works only as ON / OFF function, not as ON / OFF and DIMMER. Please adjust if possible. Many thanks in advance.

**Comment by hive** [comment]
Sorry I am not sure what you mean, each of the groups Blinds, Curtains, Sunshade and Window Coverings have both On/Off and Dim, as well as the 'proper' capabilities such as 'Window Coverings Set'. 

Which window coverings / shutters are you using? And you sure that the window coverings with in the group are using the Dim capability?

**Comment by Frankman66** [comment]
Sorry. Did not express myself correctly. Yes, all these functions are available. Unfortunately, I can not select the Qubino Shutter if ON / OFF and DIMMER are preselected. I can only select the shutter if ON / OFF is preselected, then DIMMING will not work, so intermediate positions will not work.

Shutter as mentioned above: Qubino ZMNHCD1 Flush Shutter

**Comment by hive** [comment]
Are you able to send a screenshot?

**Comment by hive** [comment]
Is this the devices you are grouping, and does the group only contain these devices?

Looks like it is a beta app : 

https://github.com/athombv/com.qubino/blob/30246888b8dbb5fa959f841a9f8e1f6fbb7804d3/drivers/ZMNHCD/driver.compose.json

**Comment by Frankman66** [comment]
OK. I try to explain...
First, I create a new group. Selection of shutters. Then the features - on / off and dimming. Result - I can not select the Qubino shutter (s). If I only select ON / OFF for the properties, I can select the shutters ...
[Shutter_Optimized.pdf](https://github.com/hive/com.groups/files/3197515/Shutter_Optimized.pdf)

**Comment by Frankman66** [comment]
And Yes! 
[qubino_flush-shutter-user-manual_v8.3_eng(1).pdf](https://github.com/hive/com.groups/files/3197527/qubino_flush-shutter-user-manual_v8.3_eng.1.pdf)
https://qubino.com/products/flush-shutter/

**Comment by Frankman66** [comment]
Using this APP - https://apps.athom.com/app/com.qubino
Latest Beta v2.0.10 - 29.01.19
with Flush Shutter (ZMNHCD)

**Comment by Frankman66** [comment]
Sorry, I told nonsense. Unfortunately, I had created a virtual switch for testing purposes. I still can not choose the Qubino shutter at all.
I will make use of virtual switches until the shutter is included. Thank you for your attention.
