### ISSUE TITLE
Device Settings : Delay

### ISSUE THREAD

**Issue by hive** [hive/com.groups#7]
Sometimes Homey messes up with working with large groups the general work around is for users to put a delay in between actions. 

This could be built in to device groups and enabled via a setting, so that users can work with large groups (delayed) but more reliable.

**Comment by Friedi1970** [comment]
It is not "sometimes" but most of the times when using large groups. Anyway, I figured out that this is, in my case, only when using the app groups. When I use the large group as individuals in one single flow I don't have a problem.
Again anyway, live with homey would be much easier if large groups would be possible!!!

**Comment by hive** [comment]
The ability to add a delay between each device update command has been added and can be modified on a group biases with in the advance settings. 

Further more a debounce was also added.
